# Generated by Django 4.0.4 on 2022-04-22 07:20

import adventure_travel_final_project.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureTravelExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters])),
                ('description', models.CharField(max_length=200, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters])),
                ('experience_picture', models.ImageField(upload_to='experiences')),
                ('category', models.CharField(choices=[('Adventure', 'Adventure'), ('Hiking', 'Hiking'), ('Sightseeing tour', 'Sightseeing tour'), ('United Kingdom', 'United Kingdom')], max_length=16)),
                ('date', models.DateField()),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('spots', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Experience',
            },
        ),
    ]
