# Generated by Django 4.0.4 on 2022-04-22 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('at_experiences', '0002_adventuretravelregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventuretravelregistration',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
