# Generated by Django 4.0.4 on 2022-04-23 09:20

import adventure_travel_final_project.common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureTravelPostAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters])),
                ('last_name', models.CharField(max_length=20, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters])),
            ],
            options={
                'verbose_name': 'Author',
            },
        ),
        migrations.CreateModel(
            name='AdventureTravelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters])),
                ('content', models.TextField(max_length=400, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters])),
                ('slug', models.SlugField(unique=True, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters])),
                ('created_on', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at_blog.adventuretravelpostauthor')),
            ],
            options={
                'verbose_name': 'Post',
            },
        ),
    ]
