# Generated by Django 4.0.4 on 2022-04-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventuretravelpost',
            name='blog_picture',
            field=models.ImageField(default=1, upload_to='blog_pictures'),
            preserve_default=False,
        ),
    ]
