# Generated by Django 4.0.4 on 2022-04-13 13:08

import adventure_travel_final_project.common.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureTravelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters, django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(blank=True, max_length=2, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters, django.core.validators.MinLengthValidator(2)])),
                ('profile_picture', models.ImageField(default='profiles/default_profile_pic.jpg', upload_to='profiles')),
                ('description', models.TextField(blank=True, null=True, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters])),
                ('country', models.CharField(blank=True, choices=[('Bulgaria', 'Bulgaria'), ('United Kingdom', 'United Kingdom'), ('Greece', 'Greece'), ('Romania', 'Romania')], max_length=14)),
                ('facebook_account', models.CharField(blank=True, max_length=40, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters])),
                ('instagram_account', models.CharField(blank=True, max_length=40, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters])),
                ('twitter_account', models.CharField(blank=True, max_length=40, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
            },
        ),
    ]
