# Generated by Django 4.0.4 on 2022-04-20 09:17

import adventure_travel_final_project.common.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('at_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventuretravelprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='adventuretravelprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
