# Generated by Django 4.0.4 on 2022-04-15 18:37

import adventure_travel_final_project.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventuretraveluser',
            name='email',
            field=models.EmailField(max_length=40, unique=True, validators=[adventure_travel_final_project.common.validators.validate_only_english_letters, django.core.validators.MinLengthValidator(5)]),
        ),
    ]
